/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dataSource.DBConnector;
import dataSource.RoomMapper;
import domain.Controller;
import domain.PayingGuest;
import domain.Room;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mads
 */
public class HotelGuiForm extends javax.swing.JFrame
{

    ArrayList<Room> room = new ArrayList<>();
    Controller control = new Controller();
    DefaultTableModel roomTableList = new DefaultTableModel();
    String Name;
    
    String[] columnNames =
    {
        "Room Number", "Room Type", "Room Cost", "Max Residents", "Cost Per Night"
    };

    public void setColumnNames(String[] columnNames)
    {
        this.columnNames = columnNames;
    }

    public String getColumnNames(int column)
    {
        return columnNames[column];
    }

    public int getColumnCount()
    {
        return 5;
    }

    public int getRowCount()
    {
        return room.size();
    }

    public Object getValueAt(int rowIndex, int columnIndex)
    {
        if (columnIndex == 0)
        {
            return room.get(rowIndex).getNumber();
        } else if (columnIndex == 1)
        {
            return room.get(rowIndex).getRoomType();
        } else if (columnIndex == 2)
        {
            return room.get(rowIndex).getId();
        } else if (columnIndex == 3)
        {
            return room.get(rowIndex).getCostPerNight();
        } else if (columnIndex == 4)
        {
            return room.get(rowIndex).getMaxResidents();
        }
        return null;
    }

    public HotelGuiForm() throws ClassNotFoundException, SQLException
    {

        initComponents();

    }

    public static void main(String[] args) throws ClassNotFoundException, SQLException
    {
        HotelGuiForm HGF = new HotelGuiForm();
        HGF.setVisible(true);

    }
    /**
     * Creates new form HotelGuiForm
     */
   
    public void hidePanels()
    {
        jPanelActivityBooking.setVisible(false);
        jPanelActivityList.setVisible(false);
        jPanelBookings.setVisible(false);
        jPanelHandballVolleyball.setVisible(false);
        jPanelMainMenu.setVisible(false);
        jPanelRegistration.setVisible(false);
        jPanelRoomAvail.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelMainMenu = new javax.swing.JPanel();
        jButtonRegistrationFormMain = new javax.swing.JButton();
        jLabelMainMenu = new javax.swing.JLabel();
        jButtonAvailMain = new javax.swing.JButton();
        jButtonBookingMain = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanelRegistration = new javax.swing.JPanel();
        jLabelRegistrationForm = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFirstName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextSurname = new javax.swing.JTextPane();
        jLabelPhone = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPhone = new javax.swing.JTextPane();
        jLabelCountry = new javax.swing.JLabel();
        jLabelAdress = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAddress = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAgency = new javax.swing.JTextPane();
        jLabelEmail = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextEmail = new javax.swing.JTextPane();
        jLabelAgency = new javax.swing.JLabel();
        jLabelCheckIn = new javax.swing.JLabel();
        jLabelNights = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jLabelDeletion = new javax.swing.JLabel();
        jButtonMainMenuReg = new javax.swing.JButton();
        jButtonRoomReg = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonRegistration = new javax.swing.JButton();
        jXDatePickerRegDateIn = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerRegDateOut = new org.jdesktop.swingx.JXDatePicker();
        jLabelRegSuccess = new javax.swing.JLabel();
        jPanelRoomAvail = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxSingle = new javax.swing.JCheckBox();
        jCheckBoxDouble = new javax.swing.JCheckBox();
        jCheckBoxFamily = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonMainMenuAvil = new javax.swing.JButton();
        jButtonRegistrationRoom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonBookRoom = new javax.swing.JButton();
        jXDatePickerAvailFrom = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerAvailTo = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelBookings = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextEmailBook = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPhoneBook = new javax.swing.JTextPane();
        jLabelAgencyBook = new javax.swing.JLabel();
        jLabelCheckInBook = new javax.swing.JLabel();
        jLabelPhoneBook = new javax.swing.JLabel();
        jButtonMainMenuBook = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextSurnameBook = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextAgencyBook = new javax.swing.JTextPane();
        jLabelSurnameBook = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextFirstNameBook = new javax.swing.JTextPane();
        jLabelEmailBook = new javax.swing.JLabel();
        jLabelNightsBook = new javax.swing.JLabel();
        jLabelCountryBook = new javax.swing.JLabel();
        jLabelAdressBook = new javax.swing.JLabel();
        jButtonRoomBook = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabelFirstNameBook = new javax.swing.JLabel();
        jLabelBookings = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextAddressBook = new javax.swing.JTextPane();
        jButtonDeleteBook = new javax.swing.JButton();
        jButtonRegBook = new javax.swing.JButton();
        jXDatePickerBookFrom = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerBookTo = new org.jdesktop.swingx.JXDatePicker();
        jPanelActivityList = new javax.swing.JPanel();
        jButtonMainMenuAvil1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonBookRoom1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelActivityBooking = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jPanelHandballVolleyball = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jButtonRegistrationFormMain.setText("Registration Form");
        jButtonRegistrationFormMain.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegistrationFormMainActionPerformed(evt);
            }
        });

        jLabelMainMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMainMenu.setText("Main Menu");

        jButtonAvailMain.setText("Room List");
        jButtonAvailMain.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAvailMainActionPerformed(evt);
            }
        });

        jButtonBookingMain.setText("Bookings");
        jButtonBookingMain.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBookingMainActionPerformed(evt);
            }
        });

        jButton5.setText("Actiivty Booking");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Activity List");
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainMenuLayout = new javax.swing.GroupLayout(jPanelMainMenu);
        jPanelMainMenu.setLayout(jPanelMainMenuLayout);
        jPanelMainMenuLayout.setHorizontalGroup(
            jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainMenuLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addGroup(jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegistrationFormMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAvailMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMainMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelMainMenu))
                    .addComponent(jButtonBookingMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanelMainMenuLayout.setVerticalGroup(
            jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrationFormMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAvailMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBookingMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMainMenu, "card2");

        jLabelRegistrationForm.setText("Booking Registration Form");
        jLabelRegistrationForm.setPreferredSize(new java.awt.Dimension(155, 18));

        jLabelFirstName.setText("First Name And Middle Name");

        jLabelSurname.setText("Surname");

        jScrollPane1.setViewportView(jTextFirstName);

        jScrollPane2.setViewportView(jTextSurname);

        jLabelPhone.setText("Phone");

        jScrollPane3.setViewportView(jTextPhone);

        jLabelCountry.setText("Country");

        jLabelAdress.setText("Address");

        jScrollPane4.setViewportView(jTextAddress);

        jScrollPane5.setViewportView(jTextAgency);

        jLabelEmail.setText("Email");

        jScrollPane6.setViewportView(jTextEmail);

        jLabelAgency.setText("Travel Agency");

        jLabelCheckIn.setText("Date of Check-In");

        jLabelNights.setText("Date of Check-Out");
        jLabelNights.setToolTipText("");

        jButtonDelete.setText("Clear Registration Form");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonMainMenuReg.setText("Main Menu");
        jButtonMainMenuReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMainMenuRegActionPerformed(evt);
            }
        });

        jButtonRoomReg.setText("Room List");
        jButtonRoomReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRoomRegActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select a country below...", "AD - Andorra", "AE - United Arab Emirates", "AF - Afghanistan", "AG - Antigua and Barbuda", "AI - Anguilla", "AL - Albania", "AM - Armenia", "AO - Angola", "AQ - Antarctica", "AR - Argentina", "AS - American Samoa", "AT - Austria", "AU - Australia", "AW - Aruba", "AZ - Azerbaijan", "BA - Bosnia and Herzegovina", "BB - Barbados", "BD - Bangladesh", "BE - Belgium", "BF - Burkina Faso", "BG - Bulgaria", "BH - Bahrain", "BI - Burundi", "BJ - Benin", "BL - Saint Barthelemy", "BM - Bermuda", "BN - Brunei", "BO - Bolivia", "BR - Brazil", "BS - Bahamas, The", "BT - Bhutan", "BV - Bouvet Island", "BW - Botswana", "BY - Belarus", "BZ - Belize", "CA - Canada", "CC - Cocos (Keeling) Islands", "CD - Congo, Democratic Republic of the", "CF - Central African Republic", "CG - Congo, Republic of the", "CH - Switzerland", "CI - Cote d'Ivoire", "CK - Cook Islands", "CL - Chile", "CM - Cameroon", "CN - China", "CO - Colombia", "CR - Costa Rica", "CU - Cuba", "CV - Cape Verde", "CW - Curacao", "CX - Christmas Island", "CY - Cyprus", "CZ - Czech Republic", "DE - Germany", "DJ - Djibouti", "DK - Denmark", "DM - Dominica", "DO - Dominican Republic", "DZ - Algeria", "EC - Ecuador", "EE - Estonia", "EG - Egypt", "EH - Western Sahara", "ER - Eritrea", "ES - Spain", "ET - Ethiopia", "FI - Finland", "FJ - Fiji", "FK - Falkland Islands (Islas Malvinas)", "FM - Micronesia, Federated States of", "FO - Faroe Islands", "FR - France", "FX - France, Metropolitan", "GA - Gabon", "GB - United Kingdom", "GD - Grenada", "GE - Georgia", "GF - French Guiana", "GG - Guernsey", "GH - Ghana", "GI - Gibraltar", "GL - Greenland", "GM - Gambia, The", "GN - Guinea", "GP - Guadeloupe", "GQ - Equatorial Guinea", "GR - Greece", "GS - South Georgia and the Islands", "GT - Guatemala", "GU - Guam", "GW - Guinea-Bissau", "GY - Guyana", "HK - Hong Kong", "HM - Heard Island and McDonald Islands", "HN - Honduras", "HR - Croatia", "HT - Haiti", "HU - Hungary", "ID - Indonesia", "IE - Ireland", "IL - Israel", "IM - Isle of Man", "IN - India", "IO - British Indian Ocean Territory", "IQ - Iraq", "IR - Iran", "IS - Iceland", "IT - Italy", "JE - Jersey", "JM - Jamaica", "JO - Jordan", "JP - Japan", "KE - Kenya", "KG - Kyrgyzstan", "KH - Cambodia", "KI - Kiribati", "KM - Comoros", "KN - Saint Kitts and Nevis", "KP - Korea, North", "KR - Korea, South", "KW - Kuwait", "KY - Cayman Islands", "KZ - Kazakhstan", "LA - Laos", "LB - Lebanon", "LC - Saint Lucia", "LI - Liechtenstein", "LK - Sri Lanka", "LR - Liberia", "LS - Lesotho", "LT - Lithuania", "LU - Luxembourg", "LV - Latvia", "LY - Libya", "MA - Morocco", "MC - Monaco", "MD - Moldova", "ME - Montenegro", "MF - Saint Martin", "MG - Madagascar", "MH - Marshall Islands", "MK - Macedonia", "ML - Mali", "MM - Burma", "MN - Mongolia", "MO - Macau", "MP - Northern Mariana Islands", "MQ - Martinique", "MR - Mauritania", "MS - Montserrat", "MT - Malta", "MU - Mauritius", "MV - Maldives", "MW - Malawi", "MX - Mexico", "MY - Malaysia", "MZ - Mozambique", "NA - Namibia", "NC - New Caledonia", "NE - Niger", "NF - Norfolk Island", "NG - Nigeria", "NI - Nicaragua", "NL - Netherlands", "NO - Norway", "NP - Nepal", "NR - Nauru", "NU - Niue", "NZ - New Zealand", "OM - Oman", "PA - Panama", "PE - Peru", "PF - French Polynesia", "PG - Papua New Guinea", "PH - Philippines", "PK - Pakistan", "PL - Poland", "PM - Saint Pierre and Miquelon", "PN - Pitcairn Islands", "PR - Puerto Rico", "PS - Gaza Strip", "PS - West Bank", "PT - Portugal", "PW - Palau", "PY - Paraguay", "QA - Qatar", "RE - Reunion", "RO - Romania", "RS - Serbia", "RU - Russia", "RW - Rwanda", "SA - Saudi Arabia", "SB - Solomon Islands", "SC - Seychelles", "SD - Sudan", "SE - Sweden", "SG - Singapore", "SH - Saint Helena, Ascension, and Tristan da Cunha", "SI - Slovenia", "SJ - Svalbard", "SK - Slovakia", "SL - Sierra Leone", "SM - San Marino", "SN - Senegal", "SO - Somalia", "SR - Suriname", "SS - South Sudan", "ST - Sao Tome and Principe", "SV - El Salvador", "SX - Sint Maarten", "SY - Syria", "SZ - Swaziland", "TC - Turks and Caicos Islands", "TD - Chad", "TF - French Southern and Antarctic Lands", "TG - Togo", "TH - Thailand", "TJ - Tajikistan", "TK - Tokelau", "TL - Timor-Leste", "TM - Turkmenistan", "TN - Tunisia", "TO - Tonga", "TR - Turkey", "TT - Trinidad and Tobago", "TV - Tuvalu", "TW - Taiwan", "TZ - Tanzania", "UA - Ukraine", "UG - Uganda", "UM - United States Minor Outlying Islands", "US - United States", "UY - Uruguay", "UZ - Uzbekistan", "VA - Holy See (Vatican City)", "VC - Saint Vincent and the Grenadines", "VE - Venezuela", "VG - British Virgin Islands", "VI - Virgin Islands", "VN - Vietnam", "VU - Vanuatu", "WF - Wallis and Futuna", "WS - Samoa", "XK - Kosovo", "YE - Yemen", "YT - Mayotte", "ZA - South Africa", "ZM - Zambia", "ZW - Zimbabwe" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonRegistration.setText("Create Booking");
        jButtonRegistration.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegistrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrationLayout = new javax.swing.GroupLayout(jPanelRegistration);
        jPanelRegistration.setLayout(jPanelRegistrationLayout);
        jPanelRegistrationLayout.setHorizontalGroup(
            jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                .addComponent(jLabelRegistrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                                        .addComponent(jLabelFirstName)
                                        .addGap(206, 206, 206)
                                        .addComponent(jLabelSurname))
                                    .addComponent(jLabelAgency)
                                    .addComponent(jLabelCheckIn)
                                    .addComponent(jXDatePickerRegDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 407, Short.MAX_VALUE))
                            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                        .addComponent(jLabelAdress, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCountry, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jXDatePickerRegDateOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelNights))
                                        .addGap(4, 4, 4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane6)
                                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEmail)
                                            .addComponent(jLabelPhone))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane3)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrationLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDeletion)
                        .addGap(145, 145, 145))
                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMainMenuReg)
                            .addComponent(jButtonRoomReg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelRegSuccess)
                                .addComponent(jButtonRegistration)))))
                .addContainerGap())
        );
        jPanelRegistrationLayout.setVerticalGroup(
            jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistrationForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFirstName)
                                    .addComponent(jLabelSurname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAdress))
                    .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jLabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                        .addComponent(jLabelAgency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCheckIn)
                            .addComponent(jLabelNights))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXDatePickerRegDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePickerRegDateOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabelDeletion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButtonMainMenuReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRoomReg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelRegSuccess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRegistration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)))
                .addContainerGap())
        );

        getContentPane().add(jPanelRegistration, "card3");

        jPanelRoomAvail.setPreferredSize(new java.awt.Dimension(825, 474));

        jLabel2.setText("Room Availability");

        jCheckBoxSingle.setText("Single Rooms");
        jCheckBoxSingle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBoxSingleActionPerformed(evt);
            }
        });

        jCheckBoxDouble.setText("Double Rooms");

        jCheckBoxFamily.setText("Family Rooms");

        jLabel1.setText("From");

        jLabel3.setText("To");

        jButtonMainMenuAvil.setText("Main Menu");
        jButtonMainMenuAvil.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMainMenuAvilActionPerformed(evt);
            }
        });

        jButtonRegistrationRoom.setText("Registration Form");
        jButtonRegistrationRoom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegistrationRoomActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");

        jButtonBookRoom.setText("Book Room");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Room Number", "Room Type", "Room Cost"
            }
        ));
        jScrollPane14.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelRoomAvailLayout = new javax.swing.GroupLayout(jPanelRoomAvail);
        jPanelRoomAvail.setLayout(jPanelRoomAvailLayout);
        jPanelRoomAvailLayout.setHorizontalGroup(
            jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomAvailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14)
                    .addGroup(jPanelRoomAvailLayout.createSequentialGroup()
                        .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanelRoomAvailLayout.createSequentialGroup()
                                .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxDouble)
                                    .addComponent(jCheckBoxSingle))
                                .addGap(42, 42, 42)
                                .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRoomAvailLayout.createSequentialGroup()
                                        .addComponent(jXDatePickerAvailFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jXDatePickerAvailTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRoomAvailLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel3))))
                            .addComponent(jCheckBoxFamily))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRegistrationRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBookRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMainMenuAvil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 216, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRoomAvailLayout.setVerticalGroup(
            jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRoomAvailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRoomAvailLayout.createSequentialGroup()
                        .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxSingle)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDouble)
                            .addComponent(jXDatePickerAvailFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePickerAvailTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxFamily)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRoomAvailLayout.createSequentialGroup()
                        .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButtonBookRoom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRoomAvailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMainMenuAvil)
                            .addComponent(jButtonRegistrationRoom))
                        .addContainerGap())))
        );

        getContentPane().add(jPanelRoomAvail, "card4");

        jScrollPane8.setViewportView(jTextEmailBook);

        jScrollPane9.setViewportView(jTextPhoneBook);

        jLabelAgencyBook.setText("Travel Agency");

        jLabelCheckInBook.setText("Date of Check-In");

        jLabelPhoneBook.setText("Phone");

        jButtonMainMenuBook.setText("Main Menu");
        jButtonMainMenuBook.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMainMenuBookActionPerformed(evt);
            }
        });

        jScrollPane10.setViewportView(jTextSurnameBook);

        jScrollPane11.setViewportView(jTextAgencyBook);

        jLabelSurnameBook.setText("Surname");

        jScrollPane12.setViewportView(jTextFirstNameBook);

        jLabelEmailBook.setText("Email");

        jLabelNightsBook.setText("Date of Check-Out");
        jLabelNightsBook.setToolTipText("");

        jLabelCountryBook.setText("Country");

        jLabelAdressBook.setText("Address");

        jButtonRoomBook.setText("Room List");
        jButtonRoomBook.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRoomBookActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select a country below...", "AD - Andorra", "AE - United Arab Emirates", "AF - Afghanistan", "AG - Antigua and Barbuda", "AI - Anguilla", "AL - Albania", "AM - Armenia", "AO - Angola", "AQ - Antarctica", "AR - Argentina", "AS - American Samoa", "AT - Austria", "AU - Australia", "AW - Aruba", "AZ - Azerbaijan", "BA - Bosnia and Herzegovina", "BB - Barbados", "BD - Bangladesh", "BE - Belgium", "BF - Burkina Faso", "BG - Bulgaria", "BH - Bahrain", "BI - Burundi", "BJ - Benin", "BL - Saint Barthelemy", "BM - Bermuda", "BN - Brunei", "BO - Bolivia", "BR - Brazil", "BS - Bahamas, The", "BT - Bhutan", "BV - Bouvet Island", "BW - Botswana", "BY - Belarus", "BZ - Belize", "CA - Canada", "CC - Cocos (Keeling) Islands", "CD - Congo, Democratic Republic of the", "CF - Central African Republic", "CG - Congo, Republic of the", "CH - Switzerland", "CI - Cote d'Ivoire", "CK - Cook Islands", "CL - Chile", "CM - Cameroon", "CN - China", "CO - Colombia", "CR - Costa Rica", "CU - Cuba", "CV - Cape Verde", "CW - Curacao", "CX - Christmas Island", "CY - Cyprus", "CZ - Czech Republic", "DE - Germany", "DJ - Djibouti", "DK - Denmark", "DM - Dominica", "DO - Dominican Republic", "DZ - Algeria", "EC - Ecuador", "EE - Estonia", "EG - Egypt", "EH - Western Sahara", "ER - Eritrea", "ES - Spain", "ET - Ethiopia", "FI - Finland", "FJ - Fiji", "FK - Falkland Islands (Islas Malvinas)", "FM - Micronesia, Federated States of", "FO - Faroe Islands", "FR - France", "FX - France, Metropolitan", "GA - Gabon", "GB - United Kingdom", "GD - Grenada", "GE - Georgia", "GF - French Guiana", "GG - Guernsey", "GH - Ghana", "GI - Gibraltar", "GL - Greenland", "GM - Gambia, The", "GN - Guinea", "GP - Guadeloupe", "GQ - Equatorial Guinea", "GR - Greece", "GS - South Georgia and the Islands", "GT - Guatemala", "GU - Guam", "GW - Guinea-Bissau", "GY - Guyana", "HK - Hong Kong", "HM - Heard Island and McDonald Islands", "HN - Honduras", "HR - Croatia", "HT - Haiti", "HU - Hungary", "ID - Indonesia", "IE - Ireland", "IL - Israel", "IM - Isle of Man", "IN - India", "IO - British Indian Ocean Territory", "IQ - Iraq", "IR - Iran", "IS - Iceland", "IT - Italy", "JE - Jersey", "JM - Jamaica", "JO - Jordan", "JP - Japan", "KE - Kenya", "KG - Kyrgyzstan", "KH - Cambodia", "KI - Kiribati", "KM - Comoros", "KN - Saint Kitts and Nevis", "KP - Korea, North", "KR - Korea, South", "KW - Kuwait", "KY - Cayman Islands", "KZ - Kazakhstan", "LA - Laos", "LB - Lebanon", "LC - Saint Lucia", "LI - Liechtenstein", "LK - Sri Lanka", "LR - Liberia", "LS - Lesotho", "LT - Lithuania", "LU - Luxembourg", "LV - Latvia", "LY - Libya", "MA - Morocco", "MC - Monaco", "MD - Moldova", "ME - Montenegro", "MF - Saint Martin", "MG - Madagascar", "MH - Marshall Islands", "MK - Macedonia", "ML - Mali", "MM - Burma", "MN - Mongolia", "MO - Macau", "MP - Northern Mariana Islands", "MQ - Martinique", "MR - Mauritania", "MS - Montserrat", "MT - Malta", "MU - Mauritius", "MV - Maldives", "MW - Malawi", "MX - Mexico", "MY - Malaysia", "MZ - Mozambique", "NA - Namibia", "NC - New Caledonia", "NE - Niger", "NF - Norfolk Island", "NG - Nigeria", "NI - Nicaragua", "NL - Netherlands", "NO - Norway", "NP - Nepal", "NR - Nauru", "NU - Niue", "NZ - New Zealand", "OM - Oman", "PA - Panama", "PE - Peru", "PF - French Polynesia", "PG - Papua New Guinea", "PH - Philippines", "PK - Pakistan", "PL - Poland", "PM - Saint Pierre and Miquelon", "PN - Pitcairn Islands", "PR - Puerto Rico", "PS - Gaza Strip", "PS - West Bank", "PT - Portugal", "PW - Palau", "PY - Paraguay", "QA - Qatar", "RE - Reunion", "RO - Romania", "RS - Serbia", "RU - Russia", "RW - Rwanda", "SA - Saudi Arabia", "SB - Solomon Islands", "SC - Seychelles", "SD - Sudan", "SE - Sweden", "SG - Singapore", "SH - Saint Helena, Ascension, and Tristan da Cunha", "SI - Slovenia", "SJ - Svalbard", "SK - Slovakia", "SL - Sierra Leone", "SM - San Marino", "SN - Senegal", "SO - Somalia", "SR - Suriname", "SS - South Sudan", "ST - Sao Tome and Principe", "SV - El Salvador", "SX - Sint Maarten", "SY - Syria", "SZ - Swaziland", "TC - Turks and Caicos Islands", "TD - Chad", "TF - French Southern and Antarctic Lands", "TG - Togo", "TH - Thailand", "TJ - Tajikistan", "TK - Tokelau", "TL - Timor-Leste", "TM - Turkmenistan", "TN - Tunisia", "TO - Tonga", "TR - Turkey", "TT - Trinidad and Tobago", "TV - Tuvalu", "TW - Taiwan", "TZ - Tanzania", "UA - Ukraine", "UG - Uganda", "UM - United States Minor Outlying Islands", "US - United States", "UY - Uruguay", "UZ - Uzbekistan", "VA - Holy See (Vatican City)", "VC - Saint Vincent and the Grenadines", "VE - Venezuela", "VG - British Virgin Islands", "VI - Virgin Islands", "VN - Vietnam", "VU - Vanuatu", "WF - Wallis and Futuna", "WS - Samoa", "XK - Kosovo", "YE - Yemen", "YT - Mayotte", "ZA - South Africa", "ZM - Zambia", "ZW - Zimbabwe" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabelFirstNameBook.setText("First Name And Middle Name");

        jLabelBookings.setText("Bookings");
        jLabelBookings.setPreferredSize(new java.awt.Dimension(155, 18));

        jScrollPane13.setViewportView(jTextAddressBook);

        jButtonDeleteBook.setText("Clear ");
        jButtonDeleteBook.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteBookActionPerformed(evt);
            }
        });

        jButtonRegBook.setText("Registration Form");
        jButtonRegBook.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRegBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBookingsLayout = new javax.swing.GroupLayout(jPanelBookings);
        jPanelBookings.setLayout(jPanelBookingsLayout);
        jPanelBookingsLayout.setHorizontalGroup(
            jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                        .addComponent(jLabelBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(550, 550, 550))
                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                        .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                        .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                                .addComponent(jLabelFirstNameBook)
                                                .addGap(206, 206, 206)
                                                .addComponent(jLabelSurnameBook))
                                            .addComponent(jLabelAgencyBook)
                                            .addComponent(jLabelCheckInBook)
                                            .addComponent(jXDatePickerBookFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 397, Short.MAX_VALUE))
                                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                        .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelAdressBook, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelCountryBook, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jXDatePickerBookTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabelNightsBook))
                                                .addGap(4, 4, 4)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane10)
                                            .addComponent(jScrollPane8)
                                            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelEmailBook)
                                                    .addComponent(jLabelPhoneBook))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jScrollPane9)))))
                            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                .addComponent(jButtonRegBook)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonMainMenuBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRoomBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanelBookingsLayout.setVerticalGroup(
            jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBookings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBookingsLayout.createSequentialGroup()
                        .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBookingsLayout.createSequentialGroup()
                                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFirstNameBook)
                                    .addComponent(jLabelSurnameBook))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAdressBook))
                    .addComponent(jLabelPhoneBook, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountryBook)
                    .addComponent(jLabelEmailBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAgencyBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCheckInBook)
                    .addComponent(jLabelNightsBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePickerBookFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePickerBookTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButtonRegBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMainMenuBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteBook)
                    .addComponent(jButtonRoomBook))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBookings, "card5");

        jButtonMainMenuAvil1.setText("Main Menu");
        jButtonMainMenuAvil1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMainMenuAvil1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");

        jButtonBookRoom1.setText("Book Activity");

        jLabel6.setText("Activity List");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Sport", "Time"
            }
        ));
        jScrollPane16.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelActivityListLayout = new javax.swing.GroupLayout(jPanelActivityList);
        jPanelActivityList.setLayout(jPanelActivityListLayout);
        jPanelActivityListLayout.setHorizontalGroup(
            jPanelActivityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActivityListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActivityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActivityListLayout.createSequentialGroup()
                        .addGap(0, 595, Short.MAX_VALUE)
                        .addComponent(jButtonBookRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelActivityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMainMenuAvil1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanelActivityListLayout.createSequentialGroup()
                        .addGroup(jPanelActivityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelActivityListLayout.setVerticalGroup(
            jPanelActivityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActivityListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelActivityListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMainMenuAvil1)
                    .addComponent(jButtonBookRoom1))
                .addContainerGap())
        );

        getContentPane().add(jPanelActivityList, "card6");

        jLabel7.setText("Activity Booking Form");

        jLabel4.setText("Sport");

        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("From");

        jLabel8.setText("To");

        jButton3.setText("Main Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sign up");

        jLabel9.setText("Number of Participants");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", " " }));

        javax.swing.GroupLayout jPanelActivityBookingLayout = new javax.swing.GroupLayout(jPanelActivityBooking);
        jPanelActivityBooking.setLayout(jPanelActivityBookingLayout);
        jPanelActivityBookingLayout.setHorizontalGroup(
            jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActivityBookingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActivityBookingLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(712, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActivityBookingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanelActivityBookingLayout.createSequentialGroup()
                        .addGroup(jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1)
                            .addComponent(jLabel9)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelActivityBookingLayout.createSequentialGroup()
                                .addGroup(jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelActivityBookingLayout.setVerticalGroup(
            jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActivityBookingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanelActivityBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelActivityBookingLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActivityBookingLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        getContentPane().add(jPanelActivityBooking, "card7");

        javax.swing.GroupLayout jPanelHandballVolleyballLayout = new javax.swing.GroupLayout(jPanelHandballVolleyball);
        jPanelHandballVolleyball.setLayout(jPanelHandballVolleyballLayout);
        jPanelHandballVolleyballLayout.setHorizontalGroup(
            jPanelHandballVolleyballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        jPanelHandballVolleyballLayout.setVerticalGroup(
            jPanelHandballVolleyballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelHandballVolleyball, "card8");

        jMenu1.setText("Main");

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rooms");

        jMenuItem3.setText("Room List");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Room Booking Form");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Room Bookings");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Activities");

        jMenuItem6.setText("Activity List");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Activity Booking Form");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Handball and Volleyball");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        jTextAddress.setText("");
        jTextAgency.setText("");
        jTextEmail.setText("");
        jTextFirstName.setText("");
        jTextPhone.setText("");
        jTextSurname.setText("");
        jLabelDeletion.setText("Deletion succesful.");

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jXDatePickerInRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jXDatePickerInRegActionPerformed
    {//GEN-HEADEREND:event_jXDatePickerInRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDatePickerInRegActionPerformed

    private void jButtonMainMenuRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMainMenuRegActionPerformed
    {//GEN-HEADEREND:event_jButtonMainMenuRegActionPerformed
        // TODO add your handling code here:
        jPanelRegistration.setVisible(false);
        jPanelMainMenu.setVisible(true);
    }//GEN-LAST:event_jButtonMainMenuRegActionPerformed

    private void jButtonRegistrationFormMainActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRegistrationFormMainActionPerformed
    {//GEN-HEADEREND:event_jButtonRegistrationFormMainActionPerformed
        // TODO add your handling code here:
        jPanelMainMenu.setVisible(false);
        jPanelRegistration.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrationFormMainActionPerformed

    private void jButtonAvailMainActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAvailMainActionPerformed
    {//GEN-HEADEREND:event_jButtonAvailMainActionPerformed
        // TODO add your handling code here:
        jPanelMainMenu.setVisible(false);
        jPanelRoomAvail.setVisible(true);
    }//GEN-LAST:event_jButtonAvailMainActionPerformed

    private void jButtonRoomRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRoomRegActionPerformed
    {//GEN-HEADEREND:event_jButtonRoomRegActionPerformed
        // TODO add your handling code here:
        jPanelRegistration.setVisible(false);
        jPanelRoomAvail.setVisible(true);

    }//GEN-LAST:event_jButtonRoomRegActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
    {//GEN-HEADEREND:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonMainMenuBookActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMainMenuBookActionPerformed
    {//GEN-HEADEREND:event_jButtonMainMenuBookActionPerformed
        // TODO add your handling code here:
        jPanelBookings.setVisible(false);
        jPanelMainMenu.setVisible(true);
    }//GEN-LAST:event_jButtonMainMenuBookActionPerformed

    private void jButtonRoomBookActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRoomBookActionPerformed
    {//GEN-HEADEREND:event_jButtonRoomBookActionPerformed
        // TODO add your handling code here:
        jPanelBookings.setVisible(false);
        jPanelRoomAvail.setVisible(true);
    }//GEN-LAST:event_jButtonRoomBookActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox2ActionPerformed
    {//GEN-HEADEREND:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButtonDeleteBookActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteBookActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteBookActionPerformed

    private void jXDateArrivalBookActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jXDateArrivalBookActionPerformed
    {//GEN-HEADEREND:event_jXDateArrivalBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXDateArrivalBookActionPerformed

    private void jButtonRegBookActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRegBookActionPerformed
    {//GEN-HEADEREND:event_jButtonRegBookActionPerformed
        // TODO add your handling code here:
        jPanelBookings.setVisible(false);
        jPanelRegistration.setVisible(true);
    }//GEN-LAST:event_jButtonRegBookActionPerformed

    private void jButtonBookingMainActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBookingMainActionPerformed
    {//GEN-HEADEREND:event_jButtonBookingMainActionPerformed
        // TODO add your handling code here:
        jPanelMainMenu.setVisible(false);
        jPanelBookings.setVisible(true);
    }//GEN-LAST:event_jButtonBookingMainActionPerformed

    private void jButtonRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonRegistrationActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        hidePanels();
        jPanelMainMenu.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        hidePanels();
        jPanelRoomAvail.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonMainMenuAvil1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMainMenuAvil1ActionPerformed
    {//GEN-HEADEREND:event_jButtonMainMenuAvil1ActionPerformed
        // TODO add your handling code here:
        jPanelActivityList.setVisible(false);
        jPanelMainMenu.setVisible(true);

    }//GEN-LAST:event_jButtonMainMenuAvil1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanelActivityBooking.setVisible(false);
        jPanelMainMenu.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanelActivityBooking.setVisible(true);
        jPanelMainMenu.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanelActivityList.setVisible(true);
        jPanelMainMenu.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonRegistrationRoomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRegistrationRoomActionPerformed
    {//GEN-HEADEREND:event_jButtonRegistrationRoomActionPerformed
        // TODO add your handling code here:
        jPanelRegistration.setVisible(true);
        jPanelRoomAvail.setVisible(false);
    }//GEN-LAST:event_jButtonRegistrationRoomActionPerformed

    private void jButtonMainMenuAvilActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMainMenuAvilActionPerformed
    {//GEN-HEADEREND:event_jButtonMainMenuAvilActionPerformed
        // TODO add your handling code here:
        jPanelMainMenu.setVisible(true);
        jPanelRoomAvail.setVisible(false);
    }//GEN-LAST:event_jButtonMainMenuAvilActionPerformed

    private void jCheckBoxSingleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxSingleActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxSingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSingleActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        hidePanels();
        jPanelRegistration.setVisible(true);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem5ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        hidePanels();
        jPanelBookings.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem6ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        hidePanels();
        jPanelActivityList.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem7ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        hidePanels();
        jPanelActivityBooking.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem8ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        hidePanels();
        jPanelHandballVolleyball.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAvailMain;
    private javax.swing.JButton jButtonBookRoom;
    private javax.swing.JButton jButtonBookRoom1;
    private javax.swing.JButton jButtonBookingMain;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDeleteBook;
    private javax.swing.JButton jButtonMainMenuAvil;
    private javax.swing.JButton jButtonMainMenuAvil1;
    private javax.swing.JButton jButtonMainMenuBook;
    private javax.swing.JButton jButtonMainMenuReg;
    private javax.swing.JButton jButtonRegBook;
    private javax.swing.JButton jButtonRegistration;
    private javax.swing.JButton jButtonRegistrationFormMain;
    private javax.swing.JButton jButtonRegistrationRoom;
    private javax.swing.JButton jButtonRoomBook;
    private javax.swing.JButton jButtonRoomReg;
    private javax.swing.JCheckBox jCheckBoxDouble;
    private javax.swing.JCheckBox jCheckBoxFamily;
    private javax.swing.JCheckBox jCheckBoxSingle;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdress;
    private javax.swing.JLabel jLabelAdressBook;
    private javax.swing.JLabel jLabelAgency;
    private javax.swing.JLabel jLabelAgencyBook;
    private javax.swing.JLabel jLabelBookings;
    private javax.swing.JLabel jLabelCheckIn;
    private javax.swing.JLabel jLabelCheckInBook;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelCountryBook;
    private javax.swing.JLabel jLabelDeletion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailBook;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelFirstNameBook;
    private javax.swing.JLabel jLabelMainMenu;
    private javax.swing.JLabel jLabelNights;
    private javax.swing.JLabel jLabelNightsBook;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPhoneBook;
    private javax.swing.JLabel jLabelRegSuccess;
    private javax.swing.JLabel jLabelRegistrationForm;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JLabel jLabelSurnameBook;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanelActivityBooking;
    private javax.swing.JPanel jPanelActivityList;
    private javax.swing.JPanel jPanelBookings;
    private javax.swing.JPanel jPanelHandballVolleyball;
    private javax.swing.JPanel jPanelMainMenu;
    private javax.swing.JPanel jPanelRegistration;
    private javax.swing.JPanel jPanelRoomAvail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextAddress;
    private javax.swing.JTextPane jTextAddressBook;
    private javax.swing.JTextPane jTextAgency;
    private javax.swing.JTextPane jTextAgencyBook;
    private javax.swing.JTextPane jTextEmail;
    private javax.swing.JTextPane jTextEmailBook;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextFirstName;
    private javax.swing.JTextPane jTextFirstNameBook;
    private javax.swing.JTextPane jTextPhone;
    private javax.swing.JTextPane jTextPhoneBook;
    private javax.swing.JTextPane jTextSurname;
    private javax.swing.JTextPane jTextSurnameBook;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAvailFrom;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerAvailTo;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerBookFrom;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerBookTo;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerRegDateIn;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerRegDateOut;
    // End of variables declaration//GEN-END:variables
}
